#!/usr/bin/env sh
#set -Eeuo pipefail

rm migrate-ok

chown -R root: ../html

if [ ! -e backend/web/index.php ]; then

    echo >&2 "Yii2 not found in $PWD - copying now..."

#    if [ -n "$(find -mindepth 1 -maxdepth 1 -not -name wp-content)" ]; then
#        echo >&2 "WARNING: $PWD is not empty! (copying anyhow)"
#    fi

    git init
    git remote add docker /git
fi

git pull docker
git checkout dev

# extract early prepared vendor dir
tar -xf /vendor.tar.gz
./composer install

#./init --env=Development --overwrite=n
./init --env=Production --overwrite=y

i=0
until [ $i -gt 3 ]
do
  echo Try to migrate...
  ./yii migrate/up --interactive=0
  if [ $? -ne 0 ]; then
    if [ $i -ge 3 ]; then
      exit 1
    fi

    sleep 5
    i=$((i=i+1))
  else
    break
  fi
done

touch migrate-ok

user='www-data'
group='www-data'
chown -R "$user:$group" .

set -- php-fpm "$@"

exec "$@"
